VIDEO:
  FILE_NAME: "imgs/VID_20230612_172955.mp4" # either path to a video, or 0 for webcam
  MASKS_PATH: "masks/"
  OVERLAYS_PATH: "masks/overlay/"
  FEATURE_TYPE: "SIFT"
  MODEL_CHECKPOINT: "faster_rcnn-working-epoch.pt"
  ANNOTATIONS_PATH: "annotations_full.json"
  DEVICE: "cuda"
TRAINING:
  # One of "fasterrcnn_resnet50_fpn", "fasterrcnn_mobilenet_v3_large_fpn"
  META_ARCHITECTURE: "fasterrcnn_resnet50_fpn"
  # One of "FasterRCNN_ResNet50_FPN_Weights", "FasterRCNN_MobileNet_V3_Large_FPN_Weights"
  WEIGHTS: "FasterRCNN_ResNet50_FPN_Weights"
  NUM_CLASSES: 17
  TEST_PROPORTION: 0.2
  PARAMETERS:
    BASE_LR: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
    BATCH_SIZE: 4
    EPOCHS: 30
    STEPS: 20 #  StepLR only accepts a single number
    GAMMA: 0.1
    NUM_WORKERS: 4
  DEVICE: "cuda"
EVALUATION:
  MODEL_CHECKPOINT: "faster_rcnn-working-epoch.pt"
  BATCH_SIZE: 1
  NUM_WORKERS: 2
  DEVICE: "cuda"
DATA:
  PATH: "data"
  ANNOTATIONS_PATH: "annotations_full.json"
  SUPERCATEGORIES: ["hauptgebaeude", "karo5", "piloty", "ULB"]
  SUBCATEGORIES: ["right", "back", "left", "front"]
METHOD:
  NAME: "train" # one of execute, train, view, label
  MODE: "annotate" # if NAME=="label", either "annotate" or "review"
WANDB:
  ENTITY: "macaw"
  PROJECT: "augmented-vision"
  IGNORE: True