VIDEO:
  FILE_NAME: "imgs/VID_20230612_151251.mp4" # either path to a video, or 0 for webcam
  MASKS_PATH: "masks/"
  OVERLAYS_PATH: "masks/overlay/"
  FEATURE_TYPE: "SIFT"
  MODEL_CHECKPOINT: "mobile-net.pt"
  DOWNLOAD: False
  DEVICE: "cuda"
TRAINING:
  NUM_CLASSES: 17
DATA:
  PATH: "data"
  ANNOTATIONS_PATH: "annotations.json"
METHOD:
  NAME: "execute" # one of execute, train, view, label